services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
